### PR TITLE
feat: Specify coding style

### PR DESCRIPTION
**Pull request by J-Javan**
This commit adds project coding style to README.

### CODE REVIEW

**Comment by J-Javan** [comment]
Reopens accidentally closed pull request.

**Comment by Maxwell175** [comment]
Thank you for your contribution.

**Comment by J-Javan** [comment]
You're welcome! If you agree we could create a Gitter page for project and exchage ideas. This not only fastens project growth but also makes contribution easier. I mean having a means of communication not necceccarilly Gitter :-)

**Comment by Maxwell175** [comment]
Thanks for the suggestion.
I created a Gitter room and added the badge to the readme. Let me know if you have any other suggestions.

**Pull request merged**
